  
# This is a basic workflow to help you get started with Actions.

name: Org Audit Complete

# Controls when the workflow will run
on:
#   schedule:
#     - cron:  '0 16 * * *'  # run once a day at 23:00 PM UTC (PST 16:00 PM), only US region working hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_HEADREF: ${{ github.head_ref }}
  GITHUB_CONTEXT: ${{ toJson(github) }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make changes to pull request
        run: |
          date +%s > report.txt
          echo "DIFF_FILES=$(git diff --name-only report.txt | wc -l)" >> $GITHUB_ENV
      - name: Create Pull Request
        if: env.DIFF_FILES != '0'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: 1source-auditor
          delete-branch: true
          title: 'Audit Repos'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: mhamdan91
          reviewers: mhamdan91
          team-reviewers: |
            owners
            maintainers
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Merge Pull Request
        run: |
          echo "$GITHUB_CONTEXT"
          curl \
          -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          https://token:${{ secrets.TOKEN }}@api.github.com/repos/${{ github.repository }}/pulls/${{ steps.cpr.outputs.pull-request-number }}/merge \
          -d '{"commit_title":"Merging Auditor PR into master", "merge_method": "squash"}'
